In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# import numpy as np # linear algebra
# import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# # Input data files are available in the read-only "../input/" directory
# # For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import sys
print(sys.version)

3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]


In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp
import matplotlib.pyplot as plt

In [2]:
# loading the training dataset
fashion_mnist_train=('../input/fashionmnist/fashion-mnist_train.csv')
df=pd.read_csv(fashion_mnist_train)
df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
y_train=df.loc[:,'label']
print(y_train)
print(y_train.shape)
print(y_train.size)

x_train=df.iloc[:,1:]
print(x_train)
print(x_train.shape)

0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64
(60000,)
60000
       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       5       0   
3           0       0       0       1       2       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995       0       0       0       0       0       0       0       0       0   
59996       0       0       0       0       0       0       0       0       0   
59997       0       0       0       0       0       0       0       0       0   
59998       0

In [4]:
m,n=df.shape
print(m,n)  #m is the no of labeled examples and n is the 784 pixels with 0th column label column

60000 785


In [5]:
fashion_mnist_test=('../input/fashionmnist/fashion-mnist_test.csv')
df=pd.read_csv(fashion_mnist_test)
df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

As is evident from the dataset that rows contain the differnt labeled exaples and the columns contain the info of each pixel of the particular image of the row

In [6]:
#activation function (sigmoid)
#to introduce the non linearity in the output so as to train the model well for the complex relations
def sigmoid_activation(t):
    return 1.0/(1.0+np.exp(-t))

In [7]:
#will need the derivative while backpropagating
def sigmoid_der(t):
    return sigmoid_activation(t)*(1-sigmoid_activation(t))

In [8]:
def softmax_fun(t):
    t=np.float128(t) #for solving the probem of large exp(t)
    return np.exp(t)/np.sum(np.exp(t))

In [9]:
def initialize_param():
    #np.random.rand(a,b) makes an matrix of the size(a,b)
    w1=np.random.rand(1000,784)-0.5
    b1=np.random.rand(1000,1)-0.5
    w2=np.random.rand(10,1000)-0.5
    b2=np.random.rand(10,1)-0.5
    
    return w1,b1,w2,b2

In [27]:
def frwd_pass(w1,b1,X,w2,b2):
    output=w1.dot(X.T)+b1  
    print("Forward pass")
    print("w1 shape= ", w1.shape)
    print("w2 shape= ", w2.shape)
    print("b1 shape= ", b1.shape)
    print("b2 shape= ", b2.shape)
# each weight is multiplied to the pixels info and then added (inner product of matrices)
# task: to understand the dimension of the output matrix 
    output_act=sigmoid_activation(output)
    soft_out=w2.dot(output_act)+b2  
    soft_act=softmax_fun(soft_out)
#     print(soft_out)
    print("Forward pass")
    return output,output_act,soft_out,soft_act

In [28]:
w1,b1,w2,b2=initialize_param()
output,output_act,soft_out,soft_act=frwd_pass(w1,b1,x_train,w2,b2)
output.shape

Forward pass
w1 shape=  (1000, 784)
w2 shape=  (10, 1000)
b1 shape=  (1000, 1)
b2 shape=  (10, 1)


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.


Forward pass


(1000, 60000)

In [29]:
#one_hot_encoding function
def one_hot_encode(y):
    one_hot_y=np.zeros((y.size,y.max()+1))
    for i,ys in enumerate(y):
        one_hot_y[i][ys]=1
    return one_hot_y

In [30]:
l=one_hot_encode(y_train)
# print(one_hot_y.size)
print(l)
print(l.shape)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
(60000, 10)


In [31]:
def backprop(output,output_act,soft_out,soft_act,w1,w2,x,y):
    """function documentation
        output.shape=hidden layers nueronsxN
        output_act=hidden layers nueronsxN
        soft_out=10xN
        soft_act=10xN
        one_hot_y=Nx10
        """
    one_hot_y=one_hot_encode(y)
    print("one_hot_y= ")
    print(one_hot_y)
    d_soft_out=soft_act-one_hot_y.T
    print("d_soft_out shape= ",d_soft_out.shape)
#     print("d_soft_out= ")
#     print(d_soft_out)
    dw2=1/m*d_soft_out.dot(output_act.T)
    db2=1/m*np.sum(d_soft_out)
    d_output=w2.T.dot(d_soft_out)*sigmoid_der(output)
    print("d_o/p shape= ",d_output.shape)
#     print("d_output= ")
#     print(d_output)
    print("Backward prop")
    dw1=1/m*d_output.dot(x) #why divided by m?
#     print("dw1=")
#     print(dw1)
    db1=1/m*np.sum(d_output)
#     print("db1")
#     print(db1)
    
    

    return dw1,db1,dw2,db2

In [32]:
def update_params(dw1,db1,dw2,db2,w2,b2,w1,b1,alpha):
    
    w1_new=w1-alpha*dw1
    b1_new=b1-alpha*db1
    w2_new=w2-alpha*dw2
    b2_new=b2-alpha*db2
    
    return w1_new,b1_new,w2_new,b2_new

In [33]:
def get_predictions(soft_act):
  return np.argmax(soft_act,0)   #returns the maximum probablity label

In [34]:
def accuracy(predictions,y):
    
    print("predictions= ",predictions,"y= ",y)
    print(predictions==y)
    return np.sum(predictions==y)/y.size

In [35]:
def cost_function(predictions,y):
#     print(predictions,y)
    print((predictions-y)**2/(y.size))

In [40]:
def main_function(x,y,alpha,iterations):
    
    w1_new,b1_new,w2_new,b2_new=initialize_param()
#     print("initial w1= ",w1_new)
#     print("initial w2= ",w2_new)
#     print("initial b1= ",b1_new)
#     print("initial b2= ",b2_new)
#     w1_new=np.array(np.array_split(w1_new,100,0))
#     print("w1_new shape= ",w1_new.shape)
#     b1_new=np.array(np.array_split(b1_new,100,0))
#     print("b1_new shape= ",b1_new.shape)
#     w2_new=np.array(np.array_split(w2_new,100,0))
#     print("w2_new shape= ",w2_new.shape)
#     b2_new=np.array(np.array_split(b2_new,100,0))
#     print("b2_new shape= ",b2_new.shape)
#     w1=w1_new
#     w2=w2_new
#     b1=b1_new
#     b2=b2_new
    for i in range(iterations):
        for i in range(100):
            x=x[i]
            y=y[i]
#             w1_new=w1[i]
#             b1_new=b1[i]
#             w2_new=w2[i]
#             b2_new=b2[i]
            output,output_act,soft_out,soft_act=frwd_pass(w1_new,b1_new,x,w2_new,b2_new)
            dw1,db1,dw2,db2=backprop(output,output_act,soft_out,soft_act,w1,w2,x,y)
            w1_new,b1_new,w2_new,b2_new=update_params(dw1,db1,dw2,db2,w2,b2,w1,b1,alpha)
#         print("W1_new= ",w1_new)
#         print("W2_new= ",w2_new)
#         print("b1_new= ",b1_new)
#         print("b2_new= ",b2_new)

#         if i%5==0:
            print('Iterations',i)
            predictions=get_predictions(soft_act)
            print("accuracy= ")
            print(accuracy(predictions,y))
            print("Cost function output= ")
            print(cost_function(predictions,y))
#         print("W1_new= ",w1_new)
#         print("W2_new= ",w2_new)
#         print("b1_new= ",b1_new)
#         print("b2_new= ",b2_new)

    
    return w1,b1,w2,b2

In [57]:
x_t=np.array(np.array_split(x_train,100,0))
y_t=(np.array(np.array_split(y_train,100,0))).T
print(y_train.shape)
print(y_train)
print(y_t.shape)
print(y_t[0:2])
print(y_t[0][1])

(60000,)
0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64
(600, 100)
[[2 0 7 7 3 9 2 2 0 8 4 8 5 3 1 3 7 2 8 2 7 8 9 7 7 3 1 1 4 8 9 1 8 0 9 9
  3 4 7 3 5 9 7 0 6 4 1 4 7 0 0 1 8 2 5 7 3 7 5 9 5 2 1 5 6 5 3 4 9 3 0 0
  5 4 8 2 7 0 8 7 7 5 9 2 3 7 5 2 1 2 6 4 5 7 8 7 0 0 9 4]
 [9 7 4 0 0 7 6 0 1 1 8 5 0 7 7 7 8 1 9 4 8 8 5 2 5 8 8 5 4 1 6 4 7 0 7 7
  7 7 8 0 0 4 4 4 4 9 8 4 1 2 4 3 9 0 0 8 6 0 1 3 6 6 5 0 9 2 5 7 0 4 8 3
  6 7 5 4 8 0 8 6 7 8 7 6 3 0 0 4 1 6 7 8 1 8 1 5 2 6 4 4]]
0


In [42]:
# def main_function(x,y,alpha,iterations):
#     w1,b1,w2,b2=initialize_param()
#     i=0
#     if(i==iterations):
#         break
#     else:
#         output,output_act,soft_out,soft_act=frwd_pass(w1,b1,x,w2,b2)
#         dw1,db1,dw2,db2=backprop(output,output_act,soft_out,soft_act,w1,w2,x,y)
#         w1_new,b1_new,w2_new,b2_new=update_params(dw1,db1,dw2,db2,w2,b2,w1,b1,alpha)
        
        

In [43]:
w1,b1,w2,b2=main_function(x_t,y_t,0.08,2)

Forward pass
w1 shape=  (1000, 784)
w2 shape=  (10, 1000)
b1 shape=  (1000, 1)
b2 shape=  (10, 1)
Forward pass
one_hot_y= 
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
d_soft_out shape=  (10, 600)
d_o/p shape=  (1000, 600)
Backward prop


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.


Iterations 0
accuracy= 
predictions=  [4 0 0 4 4 4 4 0 0 4 4 1 0 1 0 0 0 4 4 0 0 0 7 0 4 0 4 4 4 4 4 0 0 7 4 0 4
 0 4 4 0 4 0 4 0 0 0 4 4 4 0 4 0 4 4 0 0 4 0 0 0 4 0 4 0 0 0 0 0 4 4 0 4 4
 0 0 7 1 0 0 4 4 4 0 0 4 0 0 0 0 0 4 7 4 0 0 4 0 4 0 4 4 4 4 0 4 4 0 4 4 4
 4 4 4 0 0 4 0 0 0 4 4 4 4 0 4 4 0 1 4 0 7 0 0 0 4 4 0 0 4 4 1 4 4 4 4 4 4
 0 4 0 0 0 0 0 4 4 0 4 0 0 4 0 4 4 0 0 0 0 0 1 4 0 4 0 4 4 4 0 0 4 4 1 4 0
 4 0 4 4 4 1 4 0 4 0 0 0 0 4 0 4 0 0 4 0 4 4 4 4 0 4 0 0 4 0 0 4 4 4 4 0 4
 4 4 7 0 0 0 4 4 0 1 4 4 0 0 7 1 7 0 4 4 0 0 0 0 4 0 7 4 0 0 4 4 4 4 0 4 4
 4 0 4 8 0 0 0 4 4 0 0 0 4 0 0 4 0 4 0 4 4 1 4 0 0 4 4 4 0 0 0 4 4 0 4 0 0
 4 4 0 4 4 0 4 0 0 4 4 0 0 1 4 0 0 4 0 0 4 4 0 0 1 7 0 4 1 4 7 4 0 0 0 0 0
 0 4 4 7 4 0 4 4 0 4 0 4 4 0 4 7 4 0 4 7 4 0 4 0 4 0 4 4 0 0 0 4 0 4 0 4 4
 0 4 1 0 0 4 4 4 4 0 0 0 0 0 0 4 4 0 4 0 0 4 4 4 0 0 0 0 4 0 4 4 0 0 4 4 0
 4 0 4 4 0 4 0 0 4 0 7 4 0 0 4 0 4 4 4 4 0 0 4 0 7 4 0 0 0 0 4 4 1 4 4 7 4
 4 0 0 0 4 1 0 0 0 4 0 4 4 1 4 0 4 4 4 4 4 0 4 4 0 0 4 4 0 0 4

TypeError: 'numpy.int64' object is not iterable

In [ ]:
def make_predictions(x,w1,b1,w2,b2):
    output,output_act,soft_out,soft_act=frwd_pass(w1,b1,X,w2,b2)
    predictions=get_predictions(soft_act)
    return predictions

def test_predictions(index,w1,b1,w2,b2):
    current_image=x_train[:,index,None]
    prediction=make_prediction(X_train[:,index,None],w1,b1,w2,b2)
    label=y_train[index]
    print("predictions: ",predictions)
    print("Label: ",label)
    
    current_image=current_image.reshape((28,28))*255
    plt.gray()
    plt.imshow(current_image,interpolation='nearest')
    plt.show()
    
    
    

In [68]:
w=np.array([[1,2,3,8],[2,4,3,2],[1,0,0,7]])
b=np.array([[3,4,4],[2,5,1],[4,1,8],[7,8,6]])
'''1 2 3 8     3 4 4
   2 4 3 2     2 5 1
   1 0 0 7     4 1 8
               7 8 6'''
x=w.dot(b)
y=b.dot(w)
print(x)
print(y)
print("w[0] is equal to: ",w[0])
print("w[0,0] is equal to: ",w[0,0])
k=w[0].dot(b)
print(k)
a=w[0].T.dot(b)
print(a)
print(a.T==k)
s=np.array([[2,1],[3,2],[4,6]])
# summation=w+s
# print(summation)

addition=np.sum(np.exp(s))
print(addition)

array=np.array([[1,2,3,8],[2,4,3,2],[1,0,0,7],[1,5,7,3],[1,30,28,17],[10,60,25,21]])
new_arr=np.array(np.array_split(array,2,0))
print("new_array= ")
print(new_arr)
print(new_arr[0].T)

xf=(np.array([[2],[5],[4],[0],[1],[7]]).T)
new_xf=np.array(np.vsplit(xf,2))
print(new_xf)
print(type(new_xf))

[[75 81 78]
 [40 47 48]
 [52 60 46]]
[[ 15  22  21  60]
 [ 13  24  21  33]
 [ 14  12  15  90]
 [ 29  46  45 114]]
w[0] is equal to:  [1 2 3 8]
w[0,0] is equal to:  1
[75 81 78]
[75 81 78]
[ True  True  True]
495.6088744753873
new_array= 
[[[ 1  2  3  8]
  [ 2  4  3  2]
  [ 1  0  0  7]]

 [[ 1  5  7  3]
  [ 1 30 28 17]
  [10 60 25 21]]]
[[1 2 1]
 [2 4 0]
 [3 3 0]
 [8 2 7]]


ValueError: array split does not result in an equal division